---
version: '3.2'
services:
  data:
    image: ns1inc/privatedns_data:${TAG}
    environment:        # keep this line if 2+ containers are on the host
      CONFIG_PORT: 3300 # keep this line if 2+ containers are on the host
    stop_grace_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "3300:3300" # http configuration
    volumes:
      - type: volume
        source: ns1data
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id                     mypop
      --server_id                  data-server
      --number_of_stats_processors 2 
    entrypoint:
      - /bin/ns1-entrypoint
  dns:
    image: ns1inc/privatedns_dns:${TAG}
    environment:        # keep this line if 2+ containers are on the host
      CONFIG_PORT: 3301 # keep this line if 2+ containers are on the host
    ports:
      - "3301:3300" # http configuration
      - "53:53/udp" # udp port for dns
      - "53:53"     # udp port for dns
    volumes:
      - type: volume
        source: ns1dns
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              mypop
      --server_id           dns-server
      --data_host           data
      --operation_mode		authoritative
      --num_trex_procs      2
      --num_metrics_procs   2
      --metrics_flush_interval 60s
      --dns_recv_buffer     0
    entrypoint:
      - /bin/ns1-entrypoint
  web:
    image: ns1inc/privatedns_web:${TAG}
    environment:        # keep this line if 2+ containers are on the host
      CONFIG_PORT: 3302 # keep this line if 2+ containers are on the host
    ports:
      - "3302:3300"     # http configuration
      - "443:443"       # https connections to portal or api
      - "80:80"         # http connections to portal or api
    volumes:
      - type: volume
        source: ns1web
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id             mypop
      --server_id          web-server
      --data_host          data
      --api_hostname       localhost
      --portal_hostname    localhost
    entrypoint:
      - /bin/ns1-entrypoint
  xfr:
    image: ns1inc/privatedns_xfr:${TAG}
    environment:         # keep this line if 2+ containers are on the host
      CONFIG_PORT: 3303  # keep this line if 2+ containers are on the host
    ports:
      - "3303:3300"    # http configuration
      - "5400:53/udp"
      - "5400:53"      # tcp zone transfers
    volumes:
      - type: volume
        source: ns1xfr
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --pop_id              mypop
      --server_id           xfr-server
      --data_host           data
    entrypoint:
      - /bin/ns1-entrypoint
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.11.0/24
volumes:
  ns1data:
  ns1web:
  ns1xfr:
  ns1dns:
