---
version: '3.2'
services:
  data:
    image: ns1inc/privatedns_data:0.2
    ports:
      - 27017:27017 # main database
      - 15672:15672 # messaging daemon admin port
      - 5672:5672 # metrics admin port
      - 3001:3000 # http configuration
      - 8086:8086 # metrics database
    environment:
      CONFIG_PORT: 3001 # http configuration
    volumes:
      - type: volume
        source: ns1data-ns1-data
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --data_username nsone
      --data_password nsone
      --number_of_stats_processors 2
  dns:
    image: ns1inc/privatedns_dns:0.2
    environment:
      CONFIG_PORT: 3002 # http configuration
    ports:
      - "3002:3000"
      - "53:53/udp"
      - "53:53"
    volumes:
      - type: volume
        source: ns1dns-data
        target: /ns1/data
        volume:
          nocopy: true
      - type: volume
        target: /ns1-images/trexd/var/lib/trex-cache
        source: ns1dns-cache
        volume:
          nocopy: true
    command: >-
      --data_username nsone
      --data_password nsone 
      --data_host data
      --num_trex_procs 2
      --num_metrics_procs 2
  web:
    image: ns1inc/privatedns_web:0.2
    ports:
      - 3003:3000
      - 443:443   # web portal
      - 80:80
    volumes:
      - type: volume
        source: ns1web-data
        target: /ns1/data
        volume:
          nocopy: true
      - type: volume
        source: ns1web-logs
        target: /ns1-images/nginx/var/log/nginx
        volume:
          nocopy: true
    environment:
      CONFIG_PORT: 3003 # http configuration
    command: >-
      --data_username nsone
      --data_password nsone 
      --data_host data
  xfr:
    image: ns1inc/privatedns_xfr:0.2
    environment:
      CONFIG_PORT: 3004 # http configuration
    ports:
      - 3004:3000   
      - 5300:5300
    volumes:
      - type: volume
        source: ns1xfr-data
        target: /ns1/data
        volume:
          nocopy: true
    command: >-
      --data_username nsone
      --data_password nsone 
      --data_host data
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.11.0/24
volumes:
  ns1data-ns1-data:
  ns1dns-data:
  ns1dns-cache:
  ns1web-data:
  ns1web-logs:
  ns1xfr-data:
